use auth_dev;

----------- Delete Tables ---------------
DROP TABLE IF EXISTS TEMPLATE_FILE;
DROP TABLE IF EXISTS ARTICLE_TYPE;
DROP TABLE IF EXISTS PUBLICATION_TITLE;
DROP TABLE IF EXISTS PUBLICATION_TYPE;
DROP TABLE IF EXISTS AUDIT_INFO;
----------- Delete Tables ---------------

----------- Create Tables ---------------
CREATE TABLE AUDIT_INFO (
	ID INT AUTO_INCREMENT,
	CREATED_BY VARCHAR(20),
	CREATED_DATE DATETIME,
	MODIFIED_BY VARCHAR(20),
	MODIFIED_DATE DATETIME,
	PRIMARY KEY (ID)
);

CREATE TABLE PUBLICATION_TYPE (
	ID INT AUTO_INCREMENT, 
	NAME VARCHAR(255),
	DESCRIPTION VARCHAR(255),
	STATUS VARCHAR(10),
	AUDIT_INFO_ID INT,
	PRIMARY KEY (ID),
	FOREIGN KEY (AUDIT_INFO_ID) REFERENCES AUDIT_INFO(ID),
    UNIQUE (NAME)
);

CREATE TABLE PUBLICATION_TITLE (
	ID INT AUTO_INCREMENT,
	NAME VARCHAR(255),
	ACRONYM VARCHAR(20),
	DESCRIPTION VARCHAR(255), 
	STATUS VARCHAR(10),
	AUDIT_INFO_ID INT,
	PUBLICATION_TYPE_ID INT,
	PRIMARY KEY (ID),
	FOREIGN KEY (PUBLICATION_TYPE_ID) REFERENCES PUBLICATION_TYPE(ID),
	FOREIGN KEY (AUDIT_INFO_ID) REFERENCES AUDIT_INFO(ID),
    UNIQUE (PUBLICATION_TYPE_ID, NAME)
);

CREATE TABLE ARTICLE_TYPE (
	ID INT AUTO_INCREMENT, 
	NAME VARCHAR(255),
	DESCRIPTION VARCHAR(255),
	STATUS VARCHAR(10),
	AUDIT_INFO_ID INT,
	PUBLICATION_TITLE_ID INT,
	PRIMARY KEY (ID),
	FOREIGN KEY (PUBLICATION_TITLE_ID) REFERENCES PUBLICATION_TITLE(ID),
	FOREIGN KEY (AUDIT_INFO_ID) REFERENCES AUDIT_INFO(ID),
    UNIQUE (PUBLICATION_TITLE_ID, NAME)
);

CREATE TABLE TEMPLATE_FILE (
	ID INT AUTO_INCREMENT, 
	FORMAT VARCHAR(30), 
	NAME VARCHAR(255),
	DESCRIPTIVE_TEXT VARCHAR(255),
	STATUS VARCHAR(10),
	AUDIT_INFO_ID INT,
	PUBLICATION_TYPE_ID INT,
	PUBLICATION_TITLE_ID INT,
	ARTICLE_TYPE_ID INT, 
	PRIMARY KEY (ID),
	FOREIGN KEY (PUBLICATION_TYPE_ID) REFERENCES PUBLICATION_TYPE(ID),
	FOREIGN KEY (PUBLICATION_TITLE_ID) REFERENCES PUBLICATION_TITLE(ID),
	FOREIGN KEY (ARTICLE_TYPE_ID) REFERENCES ARTICLE_TYPE(ID),
	FOREIGN KEY (AUDIT_INFO_ID) REFERENCES AUDIT_INFO(ID),
	UNIQUE (NAME),
	UNIQUE (PUBLICATION_TYPE_ID, FORMAT),
	UNIQUE (PUBLICATION_TITLE_ID, FORMAT),
	UNIQUE (ARTICLE_TYPE_ID, FORMAT)
);
----------- Create Tables ---------------